// <auto-generated />
using System;
using Champions.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Champions.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("AbilityPokemon", b =>
                {
                    b.Property<int>("LegalAbilitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonWithAbilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LegalAbilitiesId", "PokemonWithAbilityId");

                    b.HasIndex("PokemonWithAbilityId");

                    b.ToTable("AbilityPokemon");
                });

            modelBuilder.Entity("Champions.Core.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("Champions.Core.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentlyLegal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Champions.Core.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BasePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Champions.Core.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryType")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("MovePokemon", b =>
                {
                    b.Property<int>("CanLearnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegalMovesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CanLearnId", "LegalMovesId");

                    b.HasIndex("LegalMovesId");

                    b.ToTable("MovePokemon");
                });

            modelBuilder.Entity("AbilityPokemon", b =>
                {
                    b.HasOne("Champions.Core.Models.Ability", null)
                        .WithMany()
                        .HasForeignKey("LegalAbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Champions.Core.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonWithAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovePokemon", b =>
                {
                    b.HasOne("Champions.Core.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("CanLearnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Champions.Core.Models.Move", null)
                        .WithMany()
                        .HasForeignKey("LegalMovesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
